spring:
  application:
    name: ecommerce

  profiles:
      active: dev # 기본설정 - 개발

  data:
    redis:
      host: 127.0.0.1
      port: 6379 # 기본 포트

server:
  port: 8080 # 내장 톰캣 포트번호

jwt:
  expiryMin : 30
  refreshWeek : 1