spring:
  config:
    activate:
      on-profile: dev

  logging:
    level:
      root: DEBUG

#  h2:
#    console:
#      enabled: true # /h2-console 설정
#      path: /h2-console
  datasource:
#    driverClassName: org.h2.Driver
##    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/spring-qna-db
#    username: sa
#    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commercedb
    username: commerce
    password: Commerce&1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        connection:
          isolation: 2
  sql:
    init:
      mode: always
      #schema-locations: classpath:schema.sql
      #data-locations: classpath:data.sql

logging:
  level:
    root: INFO

# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    get:
      summary: Mock amount endpoint
      parameters:
          name: Authorization
          in: header
          description: Access token
          required: true
          schema:
            type: string
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.hhplus.ecommerce.api # url 스캔할 파일 위치
  api-docs:
    path: /api-docs
